# Generated by Django 4.0.4 on 2022-06-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shortenURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=10000)),
                ('shortened_url', models.CharField(max_length=5)),
            ],
        ),
    ]
